services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6598:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=sqlite:///inventory.db
